import mongoose from "mongoose"

const addenquirySchema = new mongoose.Schema({
  fullName:{
    type:String,
    required:true
  },
  salesName:{
    type:String,
    required:true
  },
  contact_no:{
    type:String,
    required:true
  },
  current_Address:{
    type:String,
    required:true
  },
  Category:{
    type:String,
    required:true
  },
  passingYear:{
    type:String,
  },
  tenthPercent:{
    type:String,
  },
  twelvethPercent:{
    type:String,
  },
  educationLevel:{
    type:String,
  },
  graduateCourseName:{
    type:String,
  },
  graduateCollegeName:{
    type:String,
  },
  cgpa:{
    type:String,
  },
  postCourseName:{
    type:String,
  },
  postCollegeName:{
    type:String,
  },
  courseSpecialisation:{
    type:String,
  },
  leadSource:{
    type:String,
  },
  refType:{
    type:String,
  },
  staffType:{
    type:String,
  },
  studentName:{
    type:String,
  },
  staffName:{
    type:String,
  },
  postPassingYear:{
    type:String,
  },
  response1:{
    type:String,
  },
  response2:{
    type:String,
  },
  response3:{
    type:String,
  },
  response4:{
    type:String,
  },
  response5:{
    type:String,
  },
  response6:{
    type:String,
  },
  response7:{
    type:String,
  },
  response8:{
    type:String,
  },
  response9:{
    type:String,
  },
  response10:{
    type:String,
  },
})

const addEnquirySchema = new mongoose.model("addenquirydetails", addenquirySchema)
export default addEnquirySchema;